{% set name = "flytekitplugins-awsbatch" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekitplugins-awsbatch-{{ version }}.tar.gz
  sha256: 0bab535cfd3ced0de121fd7e6fe292663c777756222a30b1b54cbbf84aa77f78

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - flytekit >=1.0.0b3,<1.2.0

test:
  imports:
    - flytekitplugins.awsbatch
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flytekitplugins-awsbatch/
  summary: This package holds the AWS Batch plugins for flytekit
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    AWS Batch plugin for Flytekit: `{{ name }}`

    PyPI: [https://pypi.org/project/flytekitplugins-awsbatch/](https://pypi.org/project/flytekitplugins-awsbatch/)

  doc_url: https://github.com/flyteorg/flytekit/tree/master/plugins
  dev_url: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-aws-batch

extra:
  recipe-maintainers:
    - sugatoray
